controller_manager:
  ros__parameters:
    update_rate: 50
    motor_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - linear_joint
      interface_name: position
      state_publish_rate: 25
      action_monitor_rate: 10
      constraints:
        goal_time: 0.5
        stopped_velocity_tolerance: 0.01
        linear_joint:
          trajectory: 0.1
          goal: 0.1
      stop_trajectory_duration: 0.5
      state_publish_rate: 25
      action_monitor_rate: 10
      allow_partial_joints_goal: true
      partial_joints_names:
        - linear_joint
